<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Villa;

class VillaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $villas = [
            [
                'name' => 'Villa Sleman Paradise',
                'description' => 'Villa modern dengan pemandangan gunung Merapi yang menawan. Dilengkapi dengan kolam renang infinity dan taman yang asri. Lokasi strategis dekat dengan objek wisata Kaliurang. Tipe: Modern, 4 kamar tidur, 3 kamar mandi, garasi 2 mobil.',
                'price' => 625000,
                'location' => 'Sleman',
                'address' => 'Jl. Kaliurang KM 8, Sleman, Yogyakarta',
                'capacity' => 8,
                'rating' => 4.8,
                'total_reviews' => 156,
                'cleanliness_score' => 4.9,
                'facilities_score' => 4.7,
                'facilities' => json_encode(['Swimming Pool', 'Garden', 'WiFi', 'Parking', 'Kitchen', 'Air Conditioning', 'TV']),
                'images' => json_encode(['villa1_1.jpg', 'villa1_2.jpg', 'villa1_3.jpg']),
                'is_active' => true,
            ],
            [
                'name' => 'Villa Bantul Heritage',
                'description' => 'Villa bergaya tradisional Jawa dengan arsitektur joglo yang autentik. Dikelilingi sawah hijau dan suasana pedesaan yang tenang. Cocok untuk yang mencari ketenangan. Tipe: Tradisional, 3 kamar tidur, 2 kamar mandi.',
                'price' => 375000,
                'location' => 'Bantul',
                'address' => 'Jl. Bantul - Imogiri, Bantul, Yogyakarta',
                'capacity' => 6,
                'rating' => 4.2,
                'total_reviews' => 89,
                'cleanliness_score' => 4.0,
                'facilities_score' => 3.8,
                'facilities' => json_encode(['Garden', 'WiFi', 'Parking', 'Kitchen', 'Traditional Architecture']),
                'images' => json_encode(['villa2_1.jpg', 'villa2_2.jpg']),
                'is_active' => true,
            ],
            [
                'name' => 'Villa Wonosari Valley',
                'description' => 'Villa resort mewah dengan view lembah yang spektakuler. Dekat dengan pantai Baron dan Kukup. Fasilitas lengkap dengan kolam renang dan BBQ area. Tipe: Resort, 5 kamar tidur, 4 kamar mandi.',
                'price' => 750000,
                'location' => 'Gunungkidul',
                'address' => 'Jl. Baron - Wonosari, Gunungkidul, Yogyakarta',
                'capacity' => 10,
                'rating' => 4.9,
                'total_reviews' => 203,
                'cleanliness_score' => 4.8,
                'facilities_score' => 4.9,
                'facilities' => json_encode(['Swimming Pool', 'Garden', 'BBQ Area', 'WiFi', 'Parking', 'Kitchen', 'Air Conditioning', 'Valley View']),
                'images' => json_encode(['villa3_1.jpg', 'villa3_2.jpg', 'villa3_3.jpg', 'villa3_4.jpg']),
                'is_active' => true,
            ],
            [
                'name' => 'Villa Kulon Progo Riverside',
                'description' => 'Villa minimalis modern di tepi sungai Progo. Design clean dan elegan dengan kolam renang menghadap sungai. Suasana tenang dan sejuk. Tipe: Minimalis, 3 kamar tidur, 2 kamar mandi.',
                'price' => 500000,
                'location' => 'Kulon Progo',
                'address' => 'Jl. Menoreh - Kalibawang, Kulon Progo, Yogyakarta',
                'capacity' => 6,
                'rating' => 4.5,
                'total_reviews' => 112,
                'cleanliness_score' => 4.6,
                'facilities_score' => 4.4,
                'facilities' => json_encode(['Swimming Pool', 'River View', 'WiFi', 'Parking', 'Kitchen', 'Air Conditioning']),
                'images' => json_encode(['villa4_1.jpg', 'villa4_2.jpg']),
                'is_active' => true,
            ],
            [
                'name' => 'Villa Malioboro Central',
                'description' => 'Villa eksklusif di jantung kota Yogyakarta. Walking distance ke Malioboro, Keraton, dan Tugu. Perfect untuk business traveler dan city explorer. Tipe: Modern, 2 kamar tidur, 2 kamar mandi.',
                'price' => 1000000,
                'location' => 'Yogyakarta Pusat',
                'address' => 'Jl. Malioboro No. 88, Yogyakarta Pusat',
                'capacity' => 4,
                'rating' => 4.7,
                'total_reviews' => 98,
                'cleanliness_score' => 4.8,
                'facilities_score' => 4.6,
                'facilities' => json_encode(['Central Location', 'WiFi', 'Parking', 'Kitchen', 'Air Conditioning', 'City View']),
                'images' => json_encode(['villa5_1.jpg', 'villa5_2.jpg']),
                'is_active' => true,
            ],
            [
                'name' => 'Villa Borobudur Sunrise',
                'description' => 'Villa keluarga besar dengan view langsung ke Candi Borobudur. Sempurna untuk family gathering dengan fasilitas lengkap dan pemandangan sunrise yang memukau. Tipe: Villa Keluarga, 6 kamar tidur, 5 kamar mandi.',
                'price' => 850000,
                'location' => 'Magelang',
                'address' => 'Jl. Borobudur - Magelang, Magelang, Jawa Tengah',
                'capacity' => 12,
                'rating' => 4.9,
                'total_reviews' => 187,
                'cleanliness_score' => 4.8,
                'facilities_score' => 4.9,
                'facilities' => json_encode(['Swimming Pool', 'Garden', 'Borobudur View', 'WiFi', 'Parking', 'Kitchen', 'Air Conditioning', 'Large Family Space']),
                'images' => json_encode(['villa6_1.jpg', 'villa6_2.jpg', 'villa6_3.jpg']),
                'is_active' => true,
            ],
            [
                'name' => 'Villa Prambanan Classic',
                'description' => 'Villa klasik dengan nuansa Jawa kuno dekat Candi Prambanan. Arsitektur tradisional yang dipadu dengan kenyamanan modern. Taman luas dengan gazebo. Tipe: Tradisional, 4 kamar tidur, 3 kamar mandi.',
                'price' => 550000,
                'location' => 'Sleman',
                'address' => 'Jl. Prambanan - Klaten, Sleman, Yogyakarta',
                'capacity' => 8,
                'rating' => 4.3,
                'total_reviews' => 134,
                'cleanliness_score' => 4.2,
                'facilities_score' => 4.1,
                'facilities' => json_encode(['Garden', 'Gazebo', 'Traditional Architecture', 'WiFi', 'Parking', 'Kitchen']),
                'images' => json_encode(['villa7_1.jpg', 'villa7_2.jpg']),
                'is_active' => true,
            ],
            [
                'name' => 'Villa Tugu Eco Lodge',
                'description' => 'Eco lodge villa dengan konsep ramah lingkungan. Surrounded by tropical garden dengan kolam renang natural. Dekat dengan Tugu Yogyakarta. Tipe: Resort, 4 kamar tidur, 3 kamar mandi.',
                'price' => 675000,
                'location' => 'Sleman',
                'address' => 'Jl. Tugu - Kaliurang KM 5, Sleman, Yogyakarta',
                'capacity' => 8,
                'rating' => 4.6,
                'total_reviews' => 165,
                'cleanliness_score' => 4.7,
                'facilities_score' => 4.5,
                'facilities' => json_encode(['Swimming Pool', 'Tropical Garden', 'Eco Friendly', 'WiFi', 'Parking', 'Kitchen', 'Natural Pool']),
                'images' => json_encode(['villa8_1.jpg', 'villa8_2.jpg', 'villa8_3.jpg']),
                'is_active' => true,
            ],
            [
                'name' => 'Villa Parangtritis Beach',
                'description' => 'Villa modern tepi pantai Parangtritis dengan akses langsung ke beach. Kolam renang infinity menghadap laut. Perfect untuk sunset lovers. Tipe: Modern, 3 kamar tidur, 3 kamar mandi.',
                'price' => 725000,
                'location' => 'Bantul',
                'address' => 'Jl. Parangtritis KM 27, Bantul, Yogyakarta',
                'capacity' => 6,
                'rating' => 4.8,
                'total_reviews' => 142,
                'cleanliness_score' => 4.7,
                'facilities_score' => 4.8,
                'facilities' => json_encode(['Swimming Pool', 'Beach Access', 'Ocean View', 'WiFi', 'Parking', 'Kitchen', 'Infinity Pool']),
                'images' => json_encode(['villa9_1.jpg', 'villa9_2.jpg', 'villa9_3.jpg']),
                'is_active' => true,
            ],
            [
                'name' => 'Villa Kota Gede Heritage',
                'description' => 'Villa heritage di pusat kerajinan perak Kotagede. Arsitektur kolonial yang terawat dengan taman dalam yang asri. Walking distance ke workshop perak. Tipe: Tradisional, 3 kamar tidur, 2 kamar mandi.',
                'price' => 425000,
                'location' => 'Bantul',
                'address' => 'Jl. Kemasan, Kota Gede, Bantul, Yogyakarta',
                'capacity' => 6,
                'rating' => 4.1,
                'total_reviews' => 76,
                'cleanliness_score' => 4.0,
                'facilities_score' => 3.9,
                'facilities' => json_encode(['Heritage Building', 'Garden', 'Cultural Area', 'WiFi', 'Parking', 'Kitchen']),
                'images' => json_encode(['villa10_1.jpg', 'villa10_2.jpg']),
                'is_active' => true,
            ],
            [
                'name' => 'Villa Merapi View Hills',
                'description' => 'Villa minimalis di lereng Merapi dengan panorama gunung yang menakjubkan. Design modern dengan material natural. Private infinity pool dengan mountain view. Tipe: Minimalis, 4 kamar tidur, 3 kamar mandi.',
                'price' => 800000,
                'location' => 'Sleman',
                'address' => 'Jl. Kaliurang KM 15, Cangkringan, Sleman, Yogyakarta',
                'capacity' => 8,
                'rating' => 4.9,
                'total_reviews' => 198,
                'cleanliness_score' => 4.8,
                'facilities_score' => 4.9,
                'facilities' => json_encode(['Swimming Pool', 'Mountain View', 'Modern Design', 'WiFi', 'Parking', 'Kitchen', 'Air Conditioning', 'Infinity Pool']),
                'images' => json_encode(['villa11_1.jpg', 'villa11_2.jpg', 'villa11_3.jpg']),
                'is_active' => true,
            ],
            [
                'name' => 'Villa Gedong Songo Retreat',
                'description' => 'Mountain retreat villa dengan udara sejuk pegunungan. Dekat dengan Candi Gedong Songo. Fasilitas spa dan hot spring natural. Tipe: Resort, 5 kamar tidur, 4 kamar mandi.',
                'price' => 925000,
                'location' => 'Semarang',
                'address' => 'Jl. Gedong Songo, Bandungan, Semarang, Jawa Tengah',
                'capacity' => 10,
                'rating' => 4.7,
                'total_reviews' => 123,
                'cleanliness_score' => 4.6,
                'facilities_score' => 4.8,
                'facilities' => json_encode(['Swimming Pool', 'Garden', 'Spa', 'Hot Spring', 'Mountain Air', 'WiFi', 'Parking', 'Kitchen']),
                'images' => json_encode(['villa12_1.jpg', 'villa12_2.jpg', 'villa12_3.jpg']),
                'is_active' => true,
            ],
        ];

        foreach ($villas as $villa) {
            Villa::create($villa);
        }
    }
}